### ISSUE TITLE
[Request] Add Doors to the List of Items

### ISSUE THREAD

**Issue by UndeadZeratul** [ganymedes01/WoodStuff#1]
Would it be possible to add multiple doors to the list of things added for each wood type?

**Comment by buttilda** [comment]
Problem with doors is that they don't just use the planks texture, they have a unique texture so they can't be dynamically generated.

**Comment by UndeadZeratul** [comment]
Aww rats.  There isn't a way you could have a template and overlay them or anything?

**Comment by buttilda** [comment]
it's possible but it wouldn't look good.
Making an overlay that works for every texture is tricky because woods come in many different colours.

**Comment by UndeadZeratul** [comment]
That's fair; it'd be cool to have automagically generated doors, but if they're not going to look good, why bother?

**Comment by buttilda** [comment]
it sure wood (get it?)
I have plans on adding more blocks in the future likr chests and signs, but doors unfortunately just aren't worth it ):

**Comment by UndeadZeratul** [comment]
How would you handle the oredict'd recipe for the vanilla chest, disable that and add new ones?  Would the vanilla chest even be craftable, or would you make your own "oak wood chest" block that takes oak wood, along with the rest of the ones you're thinking of making?

Same thing for stuff like signs.

**Comment by buttilda** [comment]
The vanilla chest would be the fail-safe recipe, it would be crafted in case you used more than one type of wood in the recipe or if you used a plank that isn't supported.

Same for signs, except the vanilla sign would be crafted with only oak (but I'll probably also add a recipe to convert to it from any other just in case there's a recipe added by other mods that uses signs).

**Comment by UndeadZeratul** [comment]
Do non-oredictionary recipes take precedence over them?

Also, this is getting more and more tangential, but if you're going to do chest recipes, would you also be adding in a recipe for the logs themselves crafted in a box shape to give 4 chests?  If I remember correctly, Extra Utilities adds something similar in for the vanilla chest, but it could be useful for here too if you're going to be adding in custom wooden chests.

**Comment by buttilda** [comment]
When checking for recipes the game jist go through the recipes list and picks the first one it finds that matches. So I just need to make sure my recipes get registered first.
