### ISSUE TITLE
Mod support requests

### ISSUE THREAD

**Issue by labpaw** [ganymedes01/WoodStuff#10]
- [x] [Enhanced Biomes](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294692-enhanced-biomes-2-5-nearly-100-new-biomes-20-10-14)
- [x] ~~[TerraFirmaCraft](http://terrafirmacraft.com/index.html)~~
- [x] [Ridiculous World](http://minecraft.curseforge.com/mc-mods/231033-ridiculous-world)
- [x] ~~Extra Utilities colored planks~~

What do you think?

**Comment by buttilda** [comment]
I don't see the point of supporting TerrafirmaCraft, it changes the chests crafitng recipes and how they work... adding new chests for them would only break their balance.

**Comment by labpaw** [comment]
Ok, good point. The rest should be good?

**Comment by buttilda** [comment]
Yup, I'll add support for the other two

**Comment by labpaw** [comment]
Also, is it possible to add support for Extra Utilities colored planks?

**Comment by buttilda** [comment]
Depends on how he coded them. I'll have a look later

**Comment by buttilda** [comment]
Extra Utilities planks have dynamic texture that get painted on the fly. Can't add support for them.
