### ISSUE TITLE
Thaumcraft integration

### ISSUE THREAD

**Issue by labpaw** [ganymedes01/WoodStuff#11]
Not sure if it possible to add aspects to automatically generated stuff but maybe? Currently all Wood Stuff stuff only have Arbor aspect. Is it possible to add Vacuos to chests, Fabrico to crafting tables, Machina to buttons and etc?

**Comment by buttilda** [comment]
It sure is possible.
Would you mind telling me exactly what aspects (and how much of them) each of the blocks have? Thaumcraft doesn't act well in dev environments, so if I just had the list it would be a lot simpler (the code for adding the aspects I already have).

**Comment by labpaw** [comment]
Yes, sure.
Buttons should have 1 Machina
Bookshelves should have 4 Arbor, 8 Cognitio and 2 Pannus
Fences should have 2 Arbor
Fence gates should have 4 Arbor, 1 Iter and 1 Machina
Pressure Plates should have 1 Arbor, 1 Sensus and 1 Machina
Chests should have 6 Arbor and 4 Vacuos
Crafting Tables should have 4 Fabrico
