### ISSUE TITLE
Use metadata?

### ISSUE THREAD

**Issue by labpaw** [ganymedes01/WoodStuff#13]
I've noticed that Wood Stuff isn't uses metadata. That makes block ids filling really fast. I'm not sure if it's possible but maybe?

**Comment by buttilda** [comment]
Probably not, since the whole thing is dynamic, and metadata can't be bigger than 15

**Comment by labpaw** [comment]
I know, I know. But maybe it's possible to somehow determine when metadata 15 was assigned then switch to another block ID?

**Comment by buttilda** [comment]
That would cause problems when mod were removed. The whole chest list would be shifted back and chaos would ensue XD

For example:
Say I have 16 chests added by Wood Stuff. 1, 2, 3, 4... and so on.
If chest 2 is added by a mod that is later removed, chest 3 will become 2, 4 will become 3 and so on. And 16 would become 15, which means it would no longer be in a separate ID, so any existing 16 chest would be destroyed.

**Comment by buttilda** [comment]
The only way around this is using TileEntities that would store what plank that block is using.
But as everyone knows, using tile entities in decoration blocks is never a good idea. It can cause lag if the block is used too much.

**Comment by labpaw** [comment]
Ah, this is a bad thing. Thanks for answer :)

**Comment by buttilda** [comment]
No problem :)
I wish there was a way. If only TileEntities weren't so laggy )=
