### ISSUE TITLE
Support for Erebus Missing Blank Types

### ISSUE THREAD

**Issue by InkDragon** [ganymedes01/WoodStuff#15]
Most of erebus woods are covered however you are missing support for Scorched, Petrified(already has an alternative chest) and Varnished planks

**Comment by buttilda** [comment]
I thnk we might be removing the varnished planks soon, I'll check with the rest of the team.
As for the petrified planks, oversight on my part. I'll add them :)

**Comment by InkDragon** [comment]
alright good to know
