### ISSUE TITLE
Thermal Expansion Sawmill Support

### ISSUE THREAD

**Issue by Akull9** [ganymedes01/WoodStuff#16]
Natura adds support for the bookshelves to be broken down back into its components using the TE Sawmill.
Could you add support for that to this mod?

**Comment by labpaw** [comment]
This is how it's done: https://github.com/progwml6/Natura/blob/master/src/main/java/mods/natura/plugins/te4/TE4Pulse.java

**Comment by buttilda** [comment]
Sure, thank you for the request. I'll add it in :)
Thanks @Adaptivity for the link, it will definitely help.

**Comment by Akull9** [comment]
Thanks!
