### ISSUE TITLE
unable to add custom woods

### ISSUE THREAD

**Issue by InkDragon** [ganymedes01/WoodStuff#4]
I'm attempting to add ancient trees/dendrology woods in the config and they don't show up. This is what I am using based on what is shown in the config

general {
    # blockName | metadata | button | fence | gate | pressurePlate | bookshelf 
    #  e.g.:Forestry:planks | 2 | true | true | true | true | false
    S:woods <
        dendrology:wood0 | 0 | true | true | true | true | true
        dendrology:wood0 | 1 | true | true | true | true | true
        dendrology:wood0 | 2 | true | true | true | true | true
        dendrology:wood0 | 3 | true | true | true | true | true
        dendrology:wood0 | 4 | true | true | true | true | true
        dendrology:wood0 | 5 | true | true | true | true | true
        dendrology:wood0 | 6 | true | true | true | true | true
        dendrology:wood0 | 7 | true | true | true | true | true
        dendrology:wood0 | 8 | true | true | true | true | true
        dendrology:wood0 | 9 | true | true | true | true | true
        dendrology:wood0 | 10 | true | true | true | true | true
        dendrology:wood0 | 11 | true | true | true | true | true
        dendrology:wood0 | 12 | true | true | true | true | true
     >
}

where the metadata is, is any number between 0 and 12 for each of the different planks added by the mod. Each entry is on it's own line, without a following comma.

**Comment by buttilda** [comment]
Does is crash or spill out anything on the logs?

**Comment by buttilda** [comment]
Fixed it.
Dendrology uses colons in it's blocks names and that breaks the block registry when WoodStuff copies those names over... Easy fix.

Also, I added support for that mod natively :)

**Comment by InkDragon** [comment]
awesome! <3 Thank you so much
