### ISSUE TITLE
I cannot seem to add blocks, no matter what I do.

### ISSUE THREAD

**Issue by Azutte** [ganymedes01/WoodStuff#6]
All my attempts create an errored file on startup, and reset the config to default.
Here's minetweaker/modtweaker reporting on the names of the blocks I want.
![2015-06-30_02 50 00](https://cloud.githubusercontent.com/assets/6581284/8586300/fbcd266c-25a1-11e5-9d7d-be35236e1444.png)
I've tried using just the first two lines, even, in case maybe it was the "." in the second group of blocks. That didn't work. I also tried removing all the spaces in the lines, and just having, like, "true|true|true|true|true", but that also did not work.

**Comment by buttilda** [comment]
somehow I broke it... I'm pretty sure it was working before.
Thanks for letting me know.

**Comment by buttilda** [comment]
Did some tweaks and tested it and this worked:
Botania:livingwood | 0 | true | true | true | true | true

**Comment by Azutte** [comment]
so can you push a build with this to Curse?

**Comment by buttilda** [comment]
Yeah will do, sorry, it's been a busy day, i only just got home.
Expect a build in a few minutes

**Comment by buttilda** [comment]
There you go:
http://minecraft.curseforge.com/mc-mods/232043-wood-stuff/files/2246253
