### ISSUE TITLE
Doesn't seem to like me using Blood Magic blocks

### ISSUE THREAD

**Issue by Azutte** [ganymedes01/WoodStuff#7]
[http://pastebin.com/wJjb0aaz](http://pastebin.com/wJjb0aaz)

**Comment by buttilda** [comment]
That crash happened inside BloodMagic, not really sure what happened there but nothing is pointing in WoodStuff's direction.
What exactly did you do?

PS.: Sorry you're having so many problems with the mod )=

**Comment by Azutte** [comment]
I added a line to use a blood magic block :(? The bizarre part is I removed the line and it's still giving me the error. That's the only thing I've changed. Do any of your recipes use 4 of the same item in a 2x2? That's the only use for the block I'm using (large bloodstone brick) so I'm thinking maybe that might be the "conflict" implied there.

**Comment by Azutte** [comment]
Also, I stop crashing (after removing the line) only once Wood Stuff is removed. I put it BACK IN, without the line in the config, and I crash again with the same error.

**Comment by Azutte** [comment]
For reference, it was AWWayofTime:largeBloodStoneBrick | 1

**Comment by WayofTime** [comment]
The issue appears to be that a recipe result decided to return a null ItemStack. It's basically assumed that any recipe needs to have a non-null item as its output. That's the reason it breaks.

**Comment by buttilda** [comment]
Problem is that I don't mess with your recipes, I may use your block in some, but I don't tweak existing ones

**Comment by buttilda** [comment]
The ItemStacks aren't null, it's the item they contain that seems to be.
Either WoodStuff is creating a block that returns a null item, or it's causing BloodMagic to create one, or it's using a BloodMagic block that has a null item in a recipe...

**Comment by buttilda** [comment]
Got it.
So the problem happens if you type a block name wrong in the config file, which causes the game to use the air block instead. You can probably guess why that would cause crashes later on...

I've added a check so that it skips anything that was typed wrong. But as a workaround, you could simply restore your config file, or check if there isn't anything in there that's invalid (maybe you were adding support for a certain mod's block that you are no longer using?)

**Comment by Azutte** [comment]
I look forward to seeing whether this allows me to open a client again.

**Comment by buttilda** [comment]
Have you tried checking the config file to make sure you haven't got any invalid entries?

**Comment by Azutte** [comment]
I've triple-checked the file and it still throws a blood magic error despite not having the line in it any more. Does something store recipes between sessions and it errors out before it has the chance to remove the old one?

**Comment by buttilda** [comment]
BloodMagic might, but the game itself doesn't.
I'll compile you a test build when I get home in a couple hours

**Comment by buttilda** [comment]
Would you mind trying this build out?
https://dl.dropboxusercontent.com/u/213747910/WoodStuff-1.0.3.jar

**Comment by Azutte** [comment]
I do feel a little weird asking all this for compatibility with a mod block that not only isn't Wood, but there isn't even a Wood in the mod.

You were right, though, I had something mistyped! I had to completely extract Blood Magic to figure this out. I got back in and discovered I had a bunch of air-based items (air bookshelves!) with fire blocks in their crafting recipes, so I went and compared what was in the creative menu to what was in the config file.

Turns out I had a period instead of a colon in one of my Thaumcraft block lines! Still kinda weird that it went and threw a Blood Magic error, but changing that seems to have worked:
![2015-07-10_12 34 51](https://cloud.githubusercontent.com/assets/6581284/8627507/699b2f04-2700-11e5-8a35-32e93162cfb6.png)

**Comment by buttilda** [comment]
Well from now on it won't' crash anything if you make a mistake, it will just skip that line :3

**Comment by Azutte** [comment]
of course :)

**Comment by Azutte** [comment]
also [air bookshelves](http://imgur.com/a/5g8Pp)
